name: Publish

on:
  push:
    branches: ['main']
  schedule:
    - cron: '0 23 1 * *'

jobs:
  publish:
    name: Build & Publish
    concurrency:
      group: ${{ github.head_ref }}-init
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install deps
        run: npm install

      - name: set release date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      - name: Generate abbr
        run: node index.js

      - name: Publish
        run: node .github/publish.js ${{ env.RELEASE_DATE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
